In [1]:
import pandas as pd
import numpy as np
import gc
import time

df=pd.read_csv("df.csv")
df.head(5)

,index,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
0,0,24700.5,406597.5,351000.0,202500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,35698.5,1293502.5,1129500.0,270000.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,6750.0,135000.0,135000.0,67500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,29686.5,312682.5,297000.0,135000.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,4,21865.5,513000.0,513000.0,121500.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
train_df = df[df['TARGET'].notnull()]
test_df = df[df['TARGET'].isnull()]
del df
gc.collect()
feats = [f for f in train_df.columns if f not in ['TARGET','SK_ID_CURR','SK_ID_BUREAU','SK_ID_PREV','index']]

In [3]:
X = train_df[feats]
y = train_df['TARGET']

In [4]:
X.head(200)

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
0,24700.5,406597.5,351000.0,202500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35698.5,1293502.5,1129500.0,270000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6750.0,135000.0,135000.0,67500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29686.5,312682.5,297000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,21865.5,513000.0,513000.0,121500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27517.5,490495.5,454500.0,99000.000,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,41301.0,1560726.0,1395000.0,171000.000,0.0,0.0,1.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,42075.0,1530000.0,1530000.0,360000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,33826.5,1019610.0,913500.0,112500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0
9,20250.0,405000.0,405000.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21177.0,652500.0,652500.0,112500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10678.5,148365.0,135000.0,38419.155,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5881.5,80865.0,67500.0,67500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28966.5,918468.0,697500.0,225000.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,32778.0,773680.5,679500.0,189000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20160.0,299772.0,247500.0,157500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26149.5,509602.5,387000.0,108000.000,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,13500.0,270000.0,270000.0,81000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0
18,7875.0,157500.0,157500.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,17563.5,544491.0,454500.0,90000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
20,21375.0,427500.0,427500.0,135000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,37561.5,1132573.5,927000.0,202500.000,0.0,0.0,0.0,1.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,32521.5,497520.0,450000.0,450000.000,0.0,0.0,0.0,0.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23850.0,239850.0,225000.0,83250.000,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,12703.5,247500.0,247500.0,135000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,11074.5,225000.0,225000.0,90000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27076.5,979992.0,702000.0,112500.000,0.0,0.0,0.0,2.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,23827.5,327024.0,270000.0,112500.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,57676.5,790830.0,675000.0,270000.000,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,9000.0,180000.0,180000.0,90000.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,18891.0,269550.0,225000.0,112500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,27193.5,450000.0,450000.0,216000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,36747.0,675000.0,675000.0,180000.000,0.0,0.0,0.0,3.0,0.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,6597.0,127350.0,112500.0,67500.000,0.0,0.0,0.0,1.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,11097.0,119925.0,112500.0,54000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,30699.0,532494.0,454500.0,81000.000,0.0,0.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,26217.0,808650.0,675000.0,63000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,25294.5,318528.0,252000.0,157500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0
178,22738.5,700830.0,585000.0,157500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,29016.0,888840.0,675000.0,180000.000,0.0,0.0,0.0,3.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,27000.0,540000.0,540000.0,180000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,25627.5,771493.5,666000.0,202500.000,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,49873.5,746280.0,675000.0,225000.000,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0
183,19930.5,278460.0,225000.0,49500.000,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,28516.5,436032.0,360000.0,202500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,8172.0,227520.0,180000.0,90000.000,0.0,0.0,5.0,0.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,6705.0,67500.0,67500.0,90000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,25321.5,254700.0,225000.0,180000.000,0.0,0.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0
188,49050.0,876078.0,765000.0,337500.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0
189,83515.5,2250000.0,2250000.0,315000.000,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,30568.5,1040985.0,909000.0,225000.000,0.0,0.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0
191,77494.5,684054.0,630000.0,225000.000,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
192,36864.0,1256400.0,900000.0,225000.000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0
193,28552.5,720000.0,720000.0,157500.000,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,13500.0,270000.0,270000.0,112500.000,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
195,55719.0,1024740.0,900000.0,292500.000,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,32364.0,1102500.0,1102500.0,121500.000,0.0,0.0,1.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0
197,16047.0,544491.0,454500.0,157500.000,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
198,20250.0,405000.0,405000.0,135000.000,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,30276.0,912240.0,787500.0,108000.000,1.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0

In [6]:
total = X.isnull().sum().sort_values(ascending = False)
percent = (X.isnull().sum() / X.isnull().count()*100).sort_values(ascending = False)
missing_X = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_X

                                                    Total    Percent
NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MAX               270454  87.950518
NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MEAN               270454  87.950518
NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MAX                270454  87.950518
NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MEAN              270454  87.950518
REFUSED_RATE_DOWN_PAYMENT_MEAN                     262339  85.311554
REFUSED_RATE_DOWN_PAYMENT_MAX                      262339  85.311554
REFUSED_AMT_DOWN_PAYMENT_MEAN                      262339  85.311554
REFUSED_AMT_DOWN_PAYMENT_MAX                       262339  85.311554
CC_AMT_PAYMENT_CURRENT_VAR                         246888  80.286953
CC_AMT_DRAWINGS_POS_CURRENT_VAR                    246814  80.262888
CC_AMT_DRAWINGS_OTHER_CURRENT_VAR                  246814  80.262888
CC_CNT_DRAWINGS_ATM_CURRENT_VAR                    246814  80.262888
CC_AMT_DRAWINGS_ATM_CURRENT_VAR                    246814  80.262888
CC_CNT_DRAWINGS_OTHER_CURRENT_VAR                  246814  80.262888
CC_CNT_DRAWINGS_POS_CURRENT_VAR                    246814  80.262888
CC_AMT_PAYMENT_CURRENT_MEAN                        246447  80.143541
CC_AMT_PAYMENT_CURRENT_MAX                         246447  80.143541
CC_CNT_DRAWINGS_POS_CURRENT_MAX                    246367  80.117526
CC_AMT_DRAWINGS_ATM_CURRENT_MEAN                   246367  80.117526
CC_CNT_DRAWINGS_OTHER_CURRENT_MEAN                 246367  80.117526
CC_CNT_DRAWINGS_ATM_CURRENT_MAX                    246367  80.117526
CC_AMT_DRAWINGS_POS_CURRENT_MAX                    246367  80.117526
CC_AMT_DRAWINGS_POS_CURRENT_MEAN                   246367  80.117526
CC_CNT_DRAWINGS_ATM_CURRENT_MEAN                   246367  80.117526
CC_AMT_DRAWINGS_OTHER_CURRENT_MAX                  246367  80.117526
CC_AMT_DRAWINGS_ATM_CURRENT_MAX                    246367  80.117526
CC_CNT_DRAWINGS_OTHER_CURRENT_MAX                  246367  80.117526
CC_CNT_DRAWINGS_POS_CURRENT_MEAN                   246367  80.117526
CC_AMT_DRAWINGS_OTHER_CURRENT_MEAN                 246367  80.117526
ACTIVE_AMT_ANNUITY_MAX                             246161  80.050535
...                                                   ...        ...
NEW_INC_PER_CHLD                                        0   0.000000
NEW_LIVE_IND_SUM                                        0   0.000000
NEW_DOC_IND_KURT                                        0   0.000000
ORGANIZATION_TYPE_Government                            0   0.000000
ORGANIZATION_TYPE_Hotel                                 0   0.000000
ORGANIZATION_TYPE_Housing                               0   0.000000
ORGANIZATION_TYPE_Industry: type 1                      0   0.000000
ORGANIZATION_TYPE_Industry: type 10                     0   0.000000
NEW_CREDIT_TO_INCOME_RATIO                              0   0.000000
EMERGENCYSTATE_MODE_Yes                                 0   0.000000
NAME_FAMILY_STATUS_Unknown                              0   0.000000
FONDKAPREMONT_MODE_not specified                        0   0.000000
NAME_FAMILY_STATUS_Single / not married                 0   0.000000
NAME_FAMILY_STATUS_Separated                            0   0.000000
NAME_FAMILY_STATUS_Married                              0   0.000000
NAME_FAMILY_STATUS_Civil marriage                       0   0.000000
NAME_EDUCATION_TYPE_Secondary / secondary special       0   0.000000
NAME_EDUCATION_TYPE_Lower secondary                     0   0.000000
NAME_EDUCATION_TYPE_Incomplete higher                   0   0.000000
NAME_EDUCATION_TYPE_Higher education                    0   0.000000
NAME_EDUCATION_TYPE_Academic degree                     0   0.000000
NAME_CONTRACT_TYPE_Revolving loans                      0   0.000000
NAME_CONTRACT_TYPE_Cash loans                           0   0.000000
HOUSETYPE_MODE_terraced house                           0   0.000000
HOUSETYPE_MODE_specific housing                         0   0.000000
HOUSETYPE_MODE_block of flats                           0   0.000000
FONDKAPREMONT_MODE_reg oper spec account                0   0.000000
FONDKAPREMONT_MODE_reg oper account                     0   0.000000
FONDKAPREMONT_MODE_org spec account                     0   0.000000
ORGANIZATION_TYPE_Emergency                             0   0.000000

[738 rows x 2 columns]

In [8]:
L=missing_X[missing_X['Total']==0]
L

                                                   Total  Percent
ORGANIZATION_TYPE_Bank                                 0      0.0
ORGANIZATION_TYPE_Mobile                               0      0.0
ORGANIZATION_TYPE_Police                               0      0.0
LIVE_REGION_NOT_WORK_REGION                            0      0.0
LIVE_CITY_NOT_WORK_CITY                                0      0.0
ORGANIZATION_TYPE_Postal                               0      0.0
ORGANIZATION_TYPE_Realtor                              0      0.0
ORGANIZATION_TYPE_Religion                             0      0.0
HOUR_APPR_PROCESS_START                                0      0.0
ORGANIZATION_TYPE_Restaurant                           0      0.0
ORGANIZATION_TYPE_School                               0      0.0
ORGANIZATION_TYPE_Security                             0      0.0
ORGANIZATION_TYPE_Security Ministries                  0      0.0
ORGANIZATION_TYPE_Self-employed                        0      0.0
ORGANIZATION_TYPE_Services                             0      0.0
FLAG_WORK_PHONE                                        0      0.0
FLAG_PHONE                                             0      0.0
FLAG_OWN_REALTY                                        0      0.0
ORGANIZATION_TYPE_Other                                0      0.0
ORGANIZATION_TYPE_Medicine                             0      0.0
ORGANIZATION_TYPE_Military                             0      0.0
FLAG_MOBIL                                             0      0.0
REG_REGION_NOT_WORK_REGION                             0      0.0
REG_REGION_NOT_LIVE_REGION                             0      0.0
REG_CITY_NOT_WORK_CITY                                 0      0.0
REG_CITY_NOT_LIVE_CITY                                 0      0.0
REGION_RATING_CLIENT_W_CITY                            0      0.0
REGION_RATING_CLIENT                                   0      0.0
REGION_POPULATION_RELATIVE                             0      0.0
ORGANIZATION_TYPE_Industry: type 3                     0      0.0
...                                                  ...      ...
NEW_INC_PER_CHLD                                       0      0.0
NEW_LIVE_IND_SUM                                       0      0.0
NEW_DOC_IND_KURT                                       0      0.0
ORGANIZATION_TYPE_Government                           0      0.0
ORGANIZATION_TYPE_Hotel                                0      0.0
ORGANIZATION_TYPE_Housing                              0      0.0
ORGANIZATION_TYPE_Industry: type 1                     0      0.0
ORGANIZATION_TYPE_Industry: type 10                    0      0.0
NEW_CREDIT_TO_INCOME_RATIO                             0      0.0
EMERGENCYSTATE_MODE_Yes                                0      0.0
NAME_FAMILY_STATUS_Unknown                             0      0.0
FONDKAPREMONT_MODE_not specified                       0      0.0
NAME_FAMILY_STATUS_Single / not married                0      0.0
NAME_FAMILY_STATUS_Separated                           0      0.0
NAME_FAMILY_STATUS_Married                             0      0.0
NAME_FAMILY_STATUS_Civil marriage                      0      0.0
NAME_EDUCATION_TYPE_Secondary / secondary special      0      0.0
NAME_EDUCATION_TYPE_Lower secondary                    0      0.0
NAME_EDUCATION_TYPE_Incomplete higher                  0      0.0
NAME_EDUCATION_TYPE_Higher education                   0      0.0
NAME_EDUCATION_TYPE_Academic degree                    0      0.0
NAME_CONTRACT_TYPE_Revolving loans                     0      0.0
NAME_CONTRACT_TYPE_Cash loans                          0      0.0
HOUSETYPE_MODE_terraced house                          0      0.0
HOUSETYPE_MODE_specific housing                        0      0.0
HOUSETYPE_MODE_block of flats                          0      0.0
FONDKAPREMONT_MODE_reg oper spec account               0      0.0
FONDKAPREMONT_MODE_reg oper account                    0      0.0
FONDKAPREMONT_MODE_org spec account                    0      0.0
ORGANIZATION_TYPE_Emergency                            0      0.0

[165 rows x 2 columns]

In [9]:
L1=L.reset_index().values
L1

array([['ORGANIZATION_TYPE_Bank', 0, 0.0],
       ['ORGANIZATION_TYPE_Mobile', 0, 0.0],
       ['ORGANIZATION_TYPE_Police', 0, 0.0],
       ['LIVE_REGION_NOT_WORK_REGION', 0, 0.0],
       ['LIVE_CITY_NOT_WORK_CITY', 0, 0.0],
       ['ORGANIZATION_TYPE_Postal', 0, 0.0],
       ['ORGANIZATION_TYPE_Realtor', 0, 0.0],
       ['ORGANIZATION_TYPE_Religion', 0, 0.0],
       ['HOUR_APPR_PROCESS_START', 0, 0.0],
       ['ORGANIZATION_TYPE_Restaurant', 0, 0.0],
       ['ORGANIZATION_TYPE_School', 0, 0.0],
       ['ORGANIZATION_TYPE_Security', 0, 0.0],
       ['ORGANIZATION_TYPE_Security Ministries', 0, 0.0],
       ['ORGANIZATION_TYPE_Self-employed', 0, 0.0],
       ['ORGANIZATION_TYPE_Services', 0, 0.0],
       ['FLAG_WORK_PHONE', 0, 0.0],
       ['FLAG_PHONE', 0, 0.0],
       ['FLAG_OWN_REALTY', 0, 0.0],
       ['ORGANIZATION_TYPE_Other', 0, 0.0],
       ['ORGANIZATION_TYPE_Medicine', 0, 0.0],
       ['ORGANIZATION_TYPE_Military', 0, 0.0],
       ['FLAG_MOBIL', 0, 0.0],
       ['REG_REGION_NOT_WORK_REGION', 0, 0.0],
       ['REG_REGION_NOT_LIVE_REGION', 0, 0.0],
       ['REG_CITY_NOT_WORK_CITY', 0, 0.0],
       ['REG_CITY_NOT_LIVE_CITY', 0, 0.0],
       ['REGION_RATING_CLIENT_W_CITY', 0, 0.0],
       ['REGION_RATING_CLIENT', 0, 0.0],
       ['REGION_POPULATION_RELATIVE', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 3', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 4', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 5', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 6', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 7', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 8', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 9', 0, 0.0],
       ['ORGANIZATION_TYPE_Insurance', 0, 0.0],
       ['ORGANIZATION_TYPE_Kindergarten', 0, 0.0],
       ['ORGANIZATION_TYPE_Legal Services', 0, 0.0],
       ['FLAG_OWN_CAR', 0, 0.0],
       ['FLAG_EMP_PHONE', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 13', 0, 0.0],
       ['FLAG_EMAIL', 0, 0.0],
       ['CODE_GENDER', 0, 0.0],
       ['CNT_CHILDREN', 0, 0.0],
       ['WALLSMATERIAL_MODE_Mixed', 0, 0.0],
       ['WALLSMATERIAL_MODE_Monolithic', 0, 0.0],
       ['WALLSMATERIAL_MODE_Others', 0, 0.0],
       ['WALLSMATERIAL_MODE_Panel', 0, 0.0],
       ['WALLSMATERIAL_MODE_Stone, brick', 0, 0.0],
       ['WALLSMATERIAL_MODE_Wooden', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_FRIDAY', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_MONDAY', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_SATURDAY', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_SUNDAY', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_THURSDAY', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_TUESDAY', 0, 0.0],
       ['AMT_INCOME_TOTAL', 0, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_WEDNESDAY', 0, 0.0],
       ['AMT_CREDIT', 0, 0.0],
       ['WALLSMATERIAL_MODE_Block', 0, 0.0],
       ['ORGANIZATION_TYPE_XNA', 0, 0.0],
       ['ORGANIZATION_TYPE_University', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 5', 0, 0.0],
       ['FLAG_DOCUMENT_3', 0, 0.0],
       ['FLAG_CONT_MOBILE', 0, 0.0],
       ['ORGANIZATION_TYPE_Telecom', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 1', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 2', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 3', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 4', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 6', 0, 0.0],
       ['DAYS_BIRTH', 0, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 7', 0, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 1', 0, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 2', 0, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 3', 0, 0.0],
       ['DAYS_REGISTRATION', 0, 0.0],
       ['DAYS_ID_PUBLISH', 0, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 4', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 2', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 12', 0, 0.0],
       ['ORGANIZATION_TYPE_Agriculture', 0, 0.0],
       ['NAME_TYPE_SUITE_Unaccompanied', 0, 0.0],
       ['NAME_TYPE_SUITE_Other_B', 0, 0.0],
       ['NAME_TYPE_SUITE_Other_A', 0, 0.0],
       ['NAME_TYPE_SUITE_Group of people', 0, 0.0],
       ['NAME_TYPE_SUITE_Family', 0, 0.0],
       ['NAME_TYPE_SUITE_Children', 0, 0.0],
       ['NAME_INCOME_TYPE_Working', 0, 0.0],
       ['NAME_INCOME_TYPE_Unemployed', 0, 0.0],
       ['NAME_INCOME_TYPE_Student', 0, 0.0],
       ['NAME_INCOME_TYPE_State servant', 0, 0.0],
       ['NAME_INCOME_TYPE_Pensioner', 0, 0.0],
       ['NAME_INCOME_TYPE_Maternity leave', 0, 0.0],
       ['NAME_INCOME_TYPE_Commercial associate', 0, 0.0],
       ['NAME_INCOME_TYPE_Businessman', 0, 0.0],
       ['NAME_HOUSING_TYPE_With parents', 0, 0.0],
       ['NAME_HOUSING_TYPE_Rented apartment', 0, 0.0],
       ['NAME_HOUSING_TYPE_Office apartment', 0, 0.0],
       ['NAME_HOUSING_TYPE_Municipal apartment', 0, 0.0],
       ['NAME_TYPE_SUITE_Spouse, partner', 0, 0.0],
       ['OCCUPATION_TYPE_Accountants', 0, 0.0],
       ['NAME_HOUSING_TYPE_Co-op apartment', 0, 0.0],
       ['OCCUPATION_TYPE_Cleaning staff', 0, 0.0],
       ['ORGANIZATION_TYPE_Advertising', 0, 0.0],
       ['OCCUPATION_TYPE_Waiters/barmen staff', 0, 0.0],
       ['OCCUPATION_TYPE_Security staff', 0, 0.0],
       ['OCCUPATION_TYPE_Secretaries', 0, 0.0],
       ['OCCUPATION_TYPE_Sales staff', 0, 0.0],
       ['OCCUPATION_TYPE_Realty agents', 0, 0.0],
       ['OCCUPATION_TYPE_Private service staff', 0, 0.0],
       ['OCCUPATION_TYPE_Medicine staff', 0, 0.0],
       ['OCCUPATION_TYPE_Managers', 0, 0.0],
       ['OCCUPATION_TYPE_Low-skill Laborers', 0, 0.0],
       ['OCCUPATION_TYPE_Laborers', 0, 0.0],
       ['OCCUPATION_TYPE_IT staff', 0, 0.0],
       ['OCCUPATION_TYPE_High skill tech staff', 0, 0.0],
       ['OCCUPATION_TYPE_HR staff', 0, 0.0],
       ['OCCUPATION_TYPE_Drivers', 0, 0.0],
       ['OCCUPATION_TYPE_Core staff', 0, 0.0],
       ['OCCUPATION_TYPE_Cooking staff', 0, 0.0],
       ['NAME_HOUSING_TYPE_House / apartment', 0, 0.0],
       ['NAME_FAMILY_STATUS_Widow', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 11', 0, 0.0],
       ['EMERGENCYSTATE_MODE_No', 0, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 1', 0, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 2', 0, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 3', 0, 0.0],
       ['NEW_SCORES_STD', 0, 0.0],
       ['ORGANIZATION_TYPE_Cleaning', 0, 0.0],
       ['ORGANIZATION_TYPE_Construction', 0, 0.0],
       ['ORGANIZATION_TYPE_Culture', 0, 0.0],
       ['ORGANIZATION_TYPE_Electricity', 0, 0.0],
       ['NEW_INC_BY_ORG', 0, 0.0],
       ['NEW_INC_PER_CHLD', 0, 0.0],
       ['NEW_LIVE_IND_SUM', 0, 0.0],
       ['NEW_DOC_IND_KURT', 0, 0.0],
       ['ORGANIZATION_TYPE_Government', 0, 0.0],
       ['ORGANIZATION_TYPE_Hotel', 0, 0.0],
       ['ORGANIZATION_TYPE_Housing', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 1', 0, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 10', 0, 0.0],
       ['NEW_CREDIT_TO_INCOME_RATIO', 0, 0.0],
       ['EMERGENCYSTATE_MODE_Yes', 0, 0.0],
       ['NAME_FAMILY_STATUS_Unknown', 0, 0.0],
       ['FONDKAPREMONT_MODE_not specified', 0, 0.0],
       ['NAME_FAMILY_STATUS_Single / not married', 0, 0.0],
       ['NAME_FAMILY_STATUS_Separated', 0, 0.0],
       ['NAME_FAMILY_STATUS_Married', 0, 0.0],
       ['NAME_FAMILY_STATUS_Civil marriage', 0, 0.0],
       ['NAME_EDUCATION_TYPE_Secondary / secondary special', 0, 0.0],
       ['NAME_EDUCATION_TYPE_Lower secondary', 0, 0.0],
       ['NAME_EDUCATION_TYPE_Incomplete higher', 0, 0.0],
       ['NAME_EDUCATION_TYPE_Higher education', 0, 0.0],
       ['NAME_EDUCATION_TYPE_Academic degree', 0, 0.0],
       ['NAME_CONTRACT_TYPE_Revolving loans', 0, 0.0],
       ['NAME_CONTRACT_TYPE_Cash loans', 0, 0.0],
       ['HOUSETYPE_MODE_terraced house', 0, 0.0],
       ['HOUSETYPE_MODE_specific housing', 0, 0.0],
       ['HOUSETYPE_MODE_block of flats', 0, 0.0],
       ['FONDKAPREMONT_MODE_reg oper spec account', 0, 0.0],
       ['FONDKAPREMONT_MODE_reg oper account', 0, 0.0],
       ['FONDKAPREMONT_MODE_org spec account', 0, 0.0],
       ['ORGANIZATION_TYPE_Emergency', 0, 0.0]], dtype=object)

In [10]:
nomiss_feats=[]
for e in range(0, L.shape[0]):
    nomiss_feats.append(L1[e][0])
nomiss_feats

['ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Police',
 'LIVE_REGION_NOT_WORK_REGION',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'ORGANIZATION_TYPE_Religion',
 'HOUR_APPR_PROCESS_START',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'FLAG_WORK_PHONE',
 'FLAG_PHONE',
 'FLAG_OWN_REALTY',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Military',
 'FLAG_MOBIL',
 'REG_REGION_NOT_WORK_REGION',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_CITY_NOT_WORK_CITY',
 'REG_CITY_NOT_LIVE_CITY',
 'REGION_RATING_CLIENT_W_CITY',
 'REGION_RATING_CLIENT',
 'REGION_POPULATION_RELATIVE',
 'ORGANIZATION_TYPE_Industry: type 3',
 'ORGANIZATION_TYPE_Industry: type 4',
 'ORGANIZATION_TYPE_Industry: type 5',
 'ORGANIZATION_TYPE_Industry: type 6',
 'ORGANIZATION_TYPE_Industry: type 7',
 'ORGANIZATION_TYPE_Industry: type 8',
 'ORGANIZATION_TYPE_Industry: type 9',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Legal Services',
 'FLAG_OWN_CAR',
 'FLAG_EMP_PHONE',
 'ORGANIZATION_TYPE_Industry: type 13',
 'FLAG_EMAIL',
 'CODE_GENDER',
 'CNT_CHILDREN',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'AMT_INCOME_TOTAL',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'AMT_CREDIT',
 'WALLSMATERIAL_MODE_Block',
 'ORGANIZATION_TYPE_XNA',
 'ORGANIZATION_TYPE_University',
 'ORGANIZATION_TYPE_Trade: type 5',
 'FLAG_DOCUMENT_3',
 'FLAG_CONT_MOBILE',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade: type 1',
 'ORGANIZATION_TYPE_Trade: type 2',
 'ORGANIZATION_TYPE_Trade: type 3',
 'ORGANIZATION_TYPE_Trade: type 4',
 'ORGANIZATION_TYPE_Trade: type 6',
 'DAYS_BIRTH',
 'ORGANIZATION_TYPE_Trade: type 7',
 'ORGANIZATION_TYPE_Transport: type 1',
 'ORGANIZATION_TYPE_Transport: type 2',
 'ORGANIZATION_TYPE_Transport: type 3',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'ORGANIZATION_TYPE_Transport: type 4',
 'ORGANIZATION_TYPE_Industry: type 2',
 'ORGANIZATION_TYPE_Industry: type 12',
 'ORGANIZATION_TYPE_Agriculture',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Family',
 'NAME_TYPE_SUITE_Children',
 'NAME_INCOME_TYPE_Working',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Businessman',
 'NAME_HOUSING_TYPE_With parents',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'NAME_TYPE_SUITE_Spouse, partner',
 'OCCUPATION_TYPE_Accountants',
 'NAME_HOUSING_TYPE_Co-op apartment',
 'OCCUPATION_TYPE_Cleaning staff',
 'ORGANIZATION_TYPE_Advertising',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'OCCUPATION_TYPE_Security staff',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_High skill tech staff',
 'OCCUPATION_TYPE_HR staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Cooking staff',
 'NAME_HOUSING_TYPE_House / apartment',
 'NAME_FAMILY_STATUS_Widow',
 'ORGANIZATION_TYPE_Industry: type 11',
 'EMERGENCYSTATE_MODE_No',
 'ORGANIZATION_TYPE_Business Entity Type 1',
 'ORGANIZATION_TYPE_Business Entity Type 2',
 'ORGANIZATION_TYPE_Business Entity Type 3',
 'NEW_SCORES_STD',
 'ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Construction',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'NEW_INC_BY_ORG',
 'NEW_INC_PER_CHLD',
 'NEW_LIVE_IND_SUM',
 'NEW_DOC_IND_KURT',
 'ORGANIZATION_TYPE_Government',
 'ORGANIZATION_TYPE_Hotel',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry: type 1',
 'ORGANIZATION_TYPE_Industry: type 10',
 'NEW_CREDIT_TO_INCOME_RATIO',
 'EMERGENCYSTATE_MODE_Yes',
 'NAME_FAMILY_STATUS_Unknown',
 'FONDKAPREMONT_MODE_not specified',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Married',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Higher education',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_Cash loans',
 'HOUSETYPE_MODE_terraced house',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_block of flats',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_org spec account',
 'ORGANIZATION_TYPE_Emergency']

In [11]:
del missing_X
del L
del L1
gc.collect()

0

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

for f in X.columns:
    if f in nomiss_feats:
        X[f] = scaler.fit_transform(X[f].values.reshape(-1,1))
X

C:\Users\Administrator\Anaconda2\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Administrator\Anaconda2\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
0,24700.5,0.090287,351000.0,0.001512,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35698.5,0.311736,1129500.0,0.002089,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6750.0,0.022472,135000.0,0.000358,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29686.5,0.066837,297000.0,0.000935,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,21865.5,0.116854,513000.0,0.000819,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,27517.5,0.111235,454500.0,0.000627,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,41301.0,0.378458,1395000.0,0.001243,0.0,0.0,1.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,42075.0,0.370787,1530000.0,0.002858,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,33826.5,0.243348,913500.0,0.000742,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74.0
9,20250.0,0.089888,405000.0,0.000935,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21177.0,0.151685,652500.0,0.000742,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,10678.5,0.025809,135000.0,0.000109,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,5881.5,0.008955,67500.0,0.000358,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,28966.5,0.218094,697500.0,0.001704,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,32778.0,0.181943,679500.0,0.001396,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20160.0,0.063613,247500.0,0.001127,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26149.5,0.116006,387000.0,0.000704,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,13500.0,0.056180,270000.0,0.000473,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0
18,7875.0,0.028090,157500.0,0.000742,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,17563.5,0.124717,454500.0,0.000550,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
20,21375.0,0.095506,427500.0,0.000935,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,37561.5,0.271554,927000.0,0.001512,0.0,0.0,0.0,1.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,32521.5,0.112989,450000.0,0.003628,0.0,0.0,0.0,0.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23850.0,0.048652,225000.0,0.000492,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,12703.5,0.050562,247500.0,0.000935,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,11074.5,0.044944,225000.0,0.000550,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27076.5,0.233456,702000.0,0.000742,0.0,0.0,0.0,2.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,23827.5,0.070418,270000.0,0.000742,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,57676.5,0.186225,675000.0,0.002089,0.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,9000.0,0.033708,180000.0,0.000550,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307477,19975.5,0.062921,297000.0,0.001704,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0
307478,34969.5,0.113749,472500.0,0.001704,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307479,16479.0,0.050506,225000.0,0.000627,0.0,0.0,0.0,0.0,0.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307480,35617.5,0.124854,450000.0,0.004397,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307481,9000.0,0.033708,180000.0,0.002089,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307482,18283.5,0.077537,270000.0,0.002281,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307483,31473.0,0.256407,936000.0,0.000781,0.0,0.0,0.0,1.0,0.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307484,13351.5,0.022472,135000.0,0.001127,0.0,0.0,0.0,2.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307485,23089.5,0.118921,450000.0,0.001704,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
307486,9148.5,0.022472,135000.0,0.000473,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307487,31522.5,0.257978,900000.0,0.000550,0.0,0.0,0.0,1.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
307488,43443.0,0.382022,1575000.0,0.004782,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,94.0
307489,37678.5,0.225160,765000.0,0.000935,0.0,0.0,0.0,1.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
307490,46858.5,0.108539,450000.0,0.002089,0.0,0.0,0.0,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307491,23773.5,0.190674,675000.0,0.001320,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0
307492,16875.0,0.073034,337500.0,0.002858,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307493,12028.5,0.056211,193500.0,0.001320,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0
307494,52168.5,0.316382,1125000.0,0.001473,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
307495,12694.5,0.044944,225000.0,0.000473,0.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307496,35982.0,0.314310,1138500.0,0.002012,0.0,0.0,1.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0
307497,11871.0,0.056067,225000.0,0.000473,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307498,10620.0,0.044944,225000.0,0.000589,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
307499,17770.5,0.075034,247500.0,0.000742,0.0,0.0,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0
307500,16096.5,0.071640,225000.0,0.001089,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.0
307501,22050.0,0.044944,225000.0,0.000742,0.0,0.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307502,27558.0,0.052360,225000.0,0.001127,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307503,12001.5,0.056067,225000.0,0.000396,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307504,29979.0,0.157969,585000.0,0.001089,0.0,1.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307505,20205.0,0.081175,319500.0,0.001243,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307506,49117.5,0.157303,675000.0,0.001127,0.0,0.0,2.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
y = scaler.fit_transform(y.values.reshape(-1,1))
y

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [0.]])

In [31]:
"""do not run"""
#labels = train_df['TARGET']
#labels = labels[:len(train_df)]
#labels

0         1.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15        0.0
16        0.0
17        0.0
18        0.0
19        0.0
20        0.0
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        1.0
27        0.0
28        0.0
29        0.0
         ...
307477    1.0
307478    0.0
307479    0.0
307480    0.0
307481    0.0
307482    0.0
307483    0.0
307484    0.0
307485    1.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    0.0
307502    0.0
307503    0.0
307504    0.0
307505    1.0
307506    0.0
Name: TARGET, Length: 307507, dtype: float64

In [35]:
"""do not run"""
# Reshape (one-hot)
#target = np.zeros([len(labels), len(np.unique(labels))])
#target[:, 0] = labels == 0
#target[:, 1] = labels == 1
#target

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [37]:
"""do not run"""
#np.where(target[:, 1] == 1)[0]

array([     0,     26,     40, ..., 307477, 307485, 307505], dtype=int64)

In [14]:
del nomiss_feats
gc.collect()

0

In [15]:
# split data
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y,test_size=0.2)#, random_state=42)

In [16]:
X_train = X_train.fillna(value = 0)
X_valid = X_valid.fillna(value = 0)
X_train

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
245727,49117.5,0.157303,675000.0,0.001704,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
151870,16839.0,0.131447,477000.0,0.001127,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
298250,9000.0,0.033708,180000.0,0.001897,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
25177,12874.5,0.104494,463500.0,0.002666,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
163341,12249.0,0.047191,234000.0,0.000435,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
57824,37800.0,0.310449,1125000.0,0.001704,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
300723,9000.0,0.033708,180000.0,0.000358,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
40209,33628.5,0.112413,427500.0,0.001320,0.0,0.0,0.0,0.0,0.0,3.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
117073,31500.0,0.146067,630000.0,0.001897,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
35108,43681.5,0.325843,1350000.0,0.001512,0.0,0.0,1.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
50431,48735.0,0.404930,1305000.0,0.001897,0.0,0.0,0.0,0.0,0.0,3.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,80.0
52474,7600.5,0.017169,90000.0,0.000550,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,36.0
189665,34749.0,0.284385,927000.0,0.001320,0.0,0.0,6.0,0.0,0.0,2.0,...,0.01087,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,92.0
42209,29704.5,0.140593,427500.0,0.000742,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
241604,15034.5,0.061652,252000.0,0.001012,0.0,0.0,0.0,0.0,0.0,7.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
26932,16654.5,0.124854,450000.0,0.000550,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
278629,52015.5,0.459888,1575000.0,0.002474,0.0,0.0,0.0,0.0,0.0,5.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
87465,22387.5,0.075721,315000.0,0.001512,0.0,0.0,0.0,0.0,0.0,8.0,...,0.00000,1.0,0.025641,1.0,0.025641,0.0,0.0,0.0,0.0,39.0
139764,27000.0,0.123596,540000.0,0.003628,0.0,0.0,0.0,0.0,0.0,7.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
189570,24412.5,0.101124,450000.0,0.001704,0.0,0.0,1.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
275911,42790.5,0.240180,900000.0,0.000742,0.0,0.0,0.0,3.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
182900,14220.0,0.052360,225000.0,0.000742,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
179093,33921.0,0.201520,688500.0,0.001627,0.0,0.0,1.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
188526,56092.5,0.262427,900000.0,0.001743,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
162735,9000.0,0.033708,180000.0,0.000358,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
59150,30271.5,0.136164,477000.0,0.000742,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
58878,22234.5,0.190674,675000.0,0.001127,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
68141,17644.5,0.030415,144000.0,0.001704,0.0,0.0,0.0,1.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
266812,30357.0,0.052360,225000.0,0.001512,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
55274,37800.0,0.310449,1125000.0,0.001512,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12085,15943.5,0.073469,238500.0,0.000473,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
284329,35158.5,0.213483,900000.0,0.001166,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
278305,50296.5,0.213092,832500.0,0.001704,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,25.0
302345,51151.5,0.107056,450000.0,0.001704,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
39652,44509.5,0.101124,450000.0,0.000550,0.0,0.0,0.0,2.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,6.0
133861,17104.5,0.134831,585000.0,0.001127,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
78562,24381.0,0.084027,315000.0,0.000742,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,78.0
93055,22500.0,0.101124,450000.0,0.002281,0.0,0.0,1.0,2.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
242851,11556.0,0.038472,157500.0,0.000742,0.0,0.0,0.0,1.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,3.0
46248,74254.5,0.661798,2250000.0,0.001704,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
247356,29254.5,0.122826,463500.0,0.001127,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,7.0
110835,38961.0,0.341331,1233000.0,0.000935,0.0,0.0,0.0,1.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
303403,31432.5,0.231056,810000.0,0.001512,0.0,0.0,1.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,7.0
123134,14890.5,0.023499,130500.0,0.000935,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
182596,16609.5,0.046000,202500.0,0.000550,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
10596,23800.5,0.192020,679500.0,0.000396,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
88795,23130.0,0.167791,598500.0,0.000742,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
65793,13500.0,0.056180,270000.0,0.001512,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
19407,36459.0,0.177326,675000.0,0.000858,0.0,0.0,0.0,1.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
214867,26275.5,0.192135,814500.0,0.000242,0.0,0.0,2.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
133708,13500.0,0.056180,270000.0,0.000935,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
208041,31923.0,0.112989,450000.0,0.001320,0.0,0.0,0.0,0.0,0.0,3.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
172701,15466.5,0.046067,229500.0,0.000627,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
134203,17563.5,0.124717,454500.0,0.000358,0.0,0.0,0.0,0.0,0.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
266110,60421.5,0.266876,900000.0,0.001704,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
90396,9000.0,0.033708,180000.0,0.001127,0.0,0.0,0.0,0.0,1.0,2.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
302552,21906.0,0.157303,675000.0,0.001320,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
209045,18909.0,0.120222,454500.0,0.000358,0.0,0.0,0.0,0.0,0.0,1.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3495,24412.5,0.101124,450000.0,0.000550,0.0,0.0,1.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
29491,28273.5,0.134831,585000.0,0.000358,0.0,0.0,0.0,0.0,0.0,0.0,...,0.00000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0

In [17]:
print (X_train.shape)
print (X_valid.shape)
print (y_train.shape)
print (y_valid.shape)

(246005, 738)
(61502, 738)
(246005, 1)
(61502, 1)

(?, 738)
WARNING:tensorflow:From C:\Users\Administrator\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\util\tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
0 nan 91.96%

In [27]:
# Build Neural Network
import tensorflow as tf
from collections import namedtuple

def  build_neural_network(hidden_units=10):
    tf.reset_default_graph()
    inputs = tf.placeholder(tf.float32, shape=[None, X_train.shape[1]]) # X_traincolumns
    labels = tf.placeholder(tf.float32, shape=[None, 1])
    learning_rate = tf.placeholder(tf.float32)
    is_training = tf.Variable(True, dtype=tf.bool)
    
    initializer = tf.contrib.layers.xavier_initializer()
    fc = tf.layers.dense(inputs, hidden_units, activation=None,kernel_initializer=initializer)
    fc = tf.layers.batch_normalization(fc, training = is_training)
    fc = tf.nn.relu(fc)
    
    logits = tf.layers.dense(fc, 1, activation = None)
    cross_entropy = tf.nn.sigmoid_cross_entropy_with_logits(labels = labels, logits = logits)
    cost = tf.reduce_mean(cross_entropy)
    
    with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):
        optimizer = tf.train.AdamOptimizer(learning_rate = learning_rate).minimize(cost)
        
    predicted = tf.nn.sigmoid(logits)
    correct_pred = tf.equal(tf.round(predicted), labels)
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
    
    # Export the nodes 
    export_nodes = ['inputs', 'labels', 'learning_rate','is_training', 'logits',
                    'cost', 'optimizer', 'predicted', 'accuracy']
    Graph = namedtuple('Graph', export_nodes)
    local_dict = locals()
    graph = Graph(*[local_dict[each] for each in export_nodes])

    return graph
    
    
model = build_neural_network()

In [28]:
def get_batch(data_x,data_y,batch_size):
    batch_n=len(data_x)//batch_size
    for i in range(batch_n):
        batch_x=data_x[i*batch_size:(i+1)*batch_size]
        batch_y=data_y[i*batch_size:(i+1)*batch_size]
        
        yield batch_x,batch_y

In [29]:
epochs = 30
train_collect = 5
train_print=train_collect*2

learning_rate_value = 0.001
batch_size=250

x_collect = []
train_loss_collect = []
train_acc_collect = []
valid_loss_collect = []
valid_acc_collect = []

saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    iteration = 0
    for e in range(epochs):
        for batch_x,batch_y in get_batch(X_train,y_train,batch_size):
            iteration+=1;
            feed ={
                model.inputs:X_train,
                model.labels:y_train,
                model.learning_rate:learning_rate_value,
                model.is_training:True
            };
            
            
            train_loss, _, train_acc = sess.run([model.cost,model.optimizer,model.accuracy], feed_dict=feed)   
            if iteration % train_collect == 0:
                x_collect.append(e)
                train_loss_collect.append(train_loss)
                train_acc_collect.append(train_acc)
                
                if iteration % train_print==0:
                     print("Epoch: {}/{}".format(e + 1, epochs),
                      "Train Loss: {:.4f}".format(train_loss),
                      "Train Acc: {:.4f}".format(train_acc))
                        
                feed = {model.inputs: X_valid,
                        model.labels: y_valid,
                        model.is_training:False
                       }
                val_loss, val_acc = sess.run([model.cost, model.accuracy], feed_dict=feed)
                valid_loss_collect.append(val_loss)
                valid_acc_collect.append(val_acc)
                
                if iteration % train_print==0:
                    print("Epoch: {}/{}".format(e + 1, epochs),
                      "Validation Loss: {:.4f}".format(val_loss),
                      "Validation Acc: {:.4f}".format(val_acc))
                

    saver.save(sess, "./home_credit.ckpt")

Epoch: 1/30 Train Loss: nan Train Acc: 0.0000
Epoch: 1/30 Validation Loss: nan Validation Acc: 0.0000
Epoch: 1/30 Train Loss: nan Train Acc: 0.0000
Epoch: 1/30 Validation Loss: nan Validation Acc: 0.0000
Epoch: 1/30 Train Loss: nan Train Acc: 0.0000
Epoch: 1/30 Validation Loss: nan Validation Acc: 0.0000

KeyboardInterrupt:

In [28]:
T = test_df[feats]
T#.head()

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
307507,20560.5,568800.0,450000.0,135000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307508,17370.0,222768.0,180000.0,99000.0,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307509,69777.0,663264.0,630000.0,202500.0,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
307510,49018.5,1575000.0,1575000.0,315000.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,49.0
307511,32067.0,625500.0,625500.0,180000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307512,34600.5,959688.0,810000.0,270000.0,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,84.0
307513,22117.5,499221.0,373500.0,180000.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307514,14220.0,180000.0,180000.0,166500.0,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307515,28957.5,364896.0,315000.0,315000.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,15.0
307516,5337.0,45000.0,45000.0,162000.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,87.0
307517,25447.5,675000.0,675000.0,67500.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307518,16848.0,261621.0,216000.0,135000.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,28.0
307519,23539.5,296280.0,225000.0,247500.0,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307520,18535.5,360000.0,360000.0,90000.0,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307521,7875.0,157500.0,157500.0,180000.0,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307522,21690.0,296280.0,225000.0,180000.0,0.0,0.0,0.0,1.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307523,26041.5,407520.0,360000.0,202500.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,79.0
307524,22117.5,499221.0,373500.0,90000.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307525,23526.0,431280.0,360000.0,225000.0,0.0,0.0,0.0,3.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307526,46741.5,478498.5,454500.0,175500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307527,19242.0,225000.0,225000.0,99000.0,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307528,16443.0,266652.0,202500.0,157500.0,0.0,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307529,27702.0,540000.0,540000.0,135000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,12.0
307530,42493.5,1313212.5,1012500.0,337500.0,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,1.0,0.142857,1.0,0.142857,0.0,0.0,0.0,0.0,7.0
307531,29245.5,539100.0,450000.0,157500.0,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
307532,12334.5,225000.0,225000.0,76500.0,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307533,10759.5,256032.0,180000.0,112500.0,0.0,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307534,25726.5,501363.0,418500.0,225000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307535,23107.5,450000.0,450000.0,90000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307536,34074.0,945000.0,945000.0,360000.0,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356221,43366.5,547272.0,495000.0,360000.0,0.0,0.0,0.0,2.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356222,57519.0,900000.0,900000.0,315000.0,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356223,16398.0,318645.0,216000.0,135000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356224,13455.0,180000.0,180000.0,81000.0,0.0,0.0,0.0,2.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356225,19530.0,360000.0,360000.0,225000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356226,35374.5,690313.5,549000.0,112500.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,15.0
356227,23134.5,323460.0,270000.0,171000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356228,37129.5,468333.0,382500.0,130500.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356229,13284.0,166500.0,166500.0,220500.0,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356230,16213.5,315000.0,315000.0,67500.0,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356231,17707.5,514710.0,387000.0,112500.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356232,24543.0,450000.0,450000.0,45000.0,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,79.0
356233,37917.0,1002339.0,846000.0,225000.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,24.0
356234,15291.0,149256.0,135000.0,180000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356235,38398.5,685386.0,585000.0,247500.0,0.0,0.0,0.0,1.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,94.0
356236,16020.0,135000.0,135000.0,81000.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356237,40824.0,445095.0,405000.0,157500.0,0.0,0.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356238,28890.0,450000.0,450000.0,112500.0,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356239,54382.5,479700.0,450000.0,189000.0,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356240,37764.0,1047771.0,904500.0,135000.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356241,46660.5,835686.0,765000.0,135000.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,14.0
356242,7411.5,109008.0,90000.0,85500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356243,48888.0,500490.0,450000.0,157500.0,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356244,28570.5,360000.0,360000.0,270000.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,23.0
356245,23112.0,252022.5,217561.5,135000.0,0.0,0.0,0.0,2.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356246,17473.5,412560.0,270000.0,121500.0,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356247,31909.5,622413.0,495000.0,157500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356248,33205.5,315000.0,315000.0,202500.0,0.0,0.0,0.0,3.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356249,25128.0,450000.0,450000.0,225000.0,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356250,24709.5,312768.0,270000.0,135000.0,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,12.0

In [40]:
total = T.isnull().sum().sort_values(ascending = False)
percent = (T.isnull().sum() / T.isnull().count()*100).sort_values(ascending = False)
missing_T = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_T

                                                   Total    Percent
NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MEAN              42841  87.889792
NEW_RATIO_PREV_RATE_DOWN_PAYMENT_MAX               42841  87.889792
NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MEAN               42841  87.889792
NEW_RATIO_PREV_AMT_DOWN_PAYMENT_MAX                42841  87.889792
REFUSED_RATE_DOWN_PAYMENT_MAX                      41309  84.746841
REFUSED_RATE_DOWN_PAYMENT_MEAN                     41309  84.746841
REFUSED_AMT_DOWN_PAYMENT_MAX                       41309  84.746841
REFUSED_AMT_DOWN_PAYMENT_MEAN                      41309  84.746841
CC_AMT_PAYMENT_CURRENT_VAR                         37761  77.467996
CC_AMT_DRAWINGS_OTHER_CURRENT_VAR                  37745  77.435172
CC_AMT_DRAWINGS_ATM_CURRENT_VAR                    37745  77.435172
CC_CNT_DRAWINGS_ATM_CURRENT_VAR                    37745  77.435172
CC_CNT_DRAWINGS_OTHER_CURRENT_VAR                  37745  77.435172
CC_CNT_DRAWINGS_POS_CURRENT_VAR                    37745  77.435172
CC_AMT_DRAWINGS_POS_CURRENT_VAR                    37745  77.435172
CC_AMT_DRAWINGS_OTHER_CURRENT_MAX                  37690  77.322337
CC_CNT_DRAWINGS_OTHER_CURRENT_MAX                  37690  77.322337
CC_CNT_DRAWINGS_OTHER_CURRENT_MEAN                 37690  77.322337
CC_CNT_DRAWINGS_ATM_CURRENT_MEAN                   37690  77.322337
CC_CNT_DRAWINGS_POS_CURRENT_MAX                    37690  77.322337
CC_CNT_DRAWINGS_POS_CURRENT_MEAN                   37690  77.322337
CC_CNT_DRAWINGS_ATM_CURRENT_MAX                    37690  77.322337
CC_AMT_DRAWINGS_ATM_CURRENT_MAX                    37690  77.322337
CC_AMT_DRAWINGS_OTHER_CURRENT_MEAN                 37690  77.322337
CC_AMT_DRAWINGS_POS_CURRENT_MEAN                   37690  77.322337
CC_AMT_DRAWINGS_ATM_CURRENT_MEAN                   37690  77.322337
CC_AMT_DRAWINGS_POS_CURRENT_MAX                    37690  77.322337
CC_AMT_PAYMENT_CURRENT_MAX                         37684  77.310028
CC_AMT_PAYMENT_CURRENT_MEAN                        37684  77.310028
NEW_CAR_TO_EMPLOY_RATIO                            34003  69.758329
...                                                  ...        ...
ORGANIZATION_TYPE_Hotel                                0   0.000000
NEW_INC_BY_ORG                                         0   0.000000
NEW_INC_PER_CHLD                                       0   0.000000
NEW_LIVE_IND_SUM                                       0   0.000000
NEW_DOC_IND_KURT                                       0   0.000000
NEW_CREDIT_TO_GOODS_RATIO                              0   0.000000
ORGANIZATION_TYPE_Housing                              0   0.000000
ORGANIZATION_TYPE_Industry: type 1                     0   0.000000
FONDKAPREMONT_MODE_not specified                       0   0.000000
FONDKAPREMONT_MODE_org spec account                    0   0.000000
FONDKAPREMONT_MODE_reg oper account                    0   0.000000
FONDKAPREMONT_MODE_reg oper spec account               0   0.000000
NAME_HOUSING_TYPE_Co-op apartment                      0   0.000000
NAME_FAMILY_STATUS_Widow                               0   0.000000
NAME_FAMILY_STATUS_Unknown                             0   0.000000
NAME_FAMILY_STATUS_Single / not married                0   0.000000
NAME_FAMILY_STATUS_Separated                           0   0.000000
NAME_FAMILY_STATUS_Married                             0   0.000000
NAME_FAMILY_STATUS_Civil marriage                      0   0.000000
NAME_EDUCATION_TYPE_Secondary / secondary special      0   0.000000
NAME_EDUCATION_TYPE_Lower secondary                    0   0.000000
NAME_EDUCATION_TYPE_Incomplete higher                  0   0.000000
NAME_EDUCATION_TYPE_Higher education                   0   0.000000
NAME_EDUCATION_TYPE_Academic degree                    0   0.000000
NAME_CONTRACT_TYPE_Revolving loans                     0   0.000000
NAME_CONTRACT_TYPE_Cash loans                          0   0.000000
HOUSETYPE_MODE_terraced house                          0   0.000000
HOUSETYPE_MODE_specific housing                        0   0.000000
HOUSETYPE_MODE_block of flats                          0   0.000000
ORGANIZATION_TYPE_Industry: type 10                    0   0.000000

[738 rows x 2 columns]

In [41]:
L2=missing_T[missing_T['Total']==0]
L2

                                                   Total  Percent
ORGANIZATION_TYPE_Cleaning                             0      0.0
ORGANIZATION_TYPE_Police                               0      0.0
ORGANIZATION_TYPE_Postal                               0      0.0
ORGANIZATION_TYPE_Realtor                              0      0.0
LIVE_REGION_NOT_WORK_REGION                            0      0.0
LIVE_CITY_NOT_WORK_CITY                                0      0.0
ORGANIZATION_TYPE_Religion                             0      0.0
ORGANIZATION_TYPE_Restaurant                           0      0.0
ORGANIZATION_TYPE_School                               0      0.0
HOUR_APPR_PROCESS_START                                0      0.0
ORGANIZATION_TYPE_Mobile                               0      0.0
ORGANIZATION_TYPE_Security                             0      0.0
ORGANIZATION_TYPE_Security Ministries                  0      0.0
ORGANIZATION_TYPE_Self-employed                        0      0.0
ORGANIZATION_TYPE_Services                             0      0.0
ORGANIZATION_TYPE_Telecom                              0      0.0
ORGANIZATION_TYPE_Trade: type 1                        0      0.0
FLAG_WORK_PHONE                                        0      0.0
FLAG_PHONE                                             0      0.0
ORGANIZATION_TYPE_Other                                0      0.0
ORGANIZATION_TYPE_Military                             0      0.0
FLAG_OWN_CAR                                           0      0.0
ORGANIZATION_TYPE_Medicine                             0      0.0
ORGANIZATION_TYPE_Industry: type 3                     0      0.0
ORGANIZATION_TYPE_Industry: type 4                     0      0.0
REG_REGION_NOT_WORK_REGION                             0      0.0
REG_REGION_NOT_LIVE_REGION                             0      0.0
REG_CITY_NOT_WORK_CITY                                 0      0.0
REG_CITY_NOT_LIVE_CITY                                 0      0.0
REGION_RATING_CLIENT_W_CITY                            0      0.0
...                                                  ...      ...
ORGANIZATION_TYPE_Hotel                                0      0.0
NEW_INC_BY_ORG                                         0      0.0
NEW_INC_PER_CHLD                                       0      0.0
NEW_LIVE_IND_SUM                                       0      0.0
NEW_DOC_IND_KURT                                       0      0.0
NEW_CREDIT_TO_GOODS_RATIO                              0      0.0
ORGANIZATION_TYPE_Housing                              0      0.0
ORGANIZATION_TYPE_Industry: type 1                     0      0.0
FONDKAPREMONT_MODE_not specified                       0      0.0
FONDKAPREMONT_MODE_org spec account                    0      0.0
FONDKAPREMONT_MODE_reg oper account                    0      0.0
FONDKAPREMONT_MODE_reg oper spec account               0      0.0
NAME_HOUSING_TYPE_Co-op apartment                      0      0.0
NAME_FAMILY_STATUS_Widow                               0      0.0
NAME_FAMILY_STATUS_Unknown                             0      0.0
NAME_FAMILY_STATUS_Single / not married                0      0.0
NAME_FAMILY_STATUS_Separated                           0      0.0
NAME_FAMILY_STATUS_Married                             0      0.0
NAME_FAMILY_STATUS_Civil marriage                      0      0.0
NAME_EDUCATION_TYPE_Secondary / secondary special      0      0.0
NAME_EDUCATION_TYPE_Lower secondary                    0      0.0
NAME_EDUCATION_TYPE_Incomplete higher                  0      0.0
NAME_EDUCATION_TYPE_Higher education                   0      0.0
NAME_EDUCATION_TYPE_Academic degree                    0      0.0
NAME_CONTRACT_TYPE_Revolving loans                     0      0.0
NAME_CONTRACT_TYPE_Cash loans                          0      0.0
HOUSETYPE_MODE_terraced house                          0      0.0
HOUSETYPE_MODE_specific housing                        0      0.0
HOUSETYPE_MODE_block of flats                          0      0.0
ORGANIZATION_TYPE_Industry: type 10                    0      0.0

[170 rows x 2 columns]

In [42]:
L3=L2.reset_index().values
L3

array([['ORGANIZATION_TYPE_Cleaning', 0L, 0.0],
       ['ORGANIZATION_TYPE_Police', 0L, 0.0],
       ['ORGANIZATION_TYPE_Postal', 0L, 0.0],
       ['ORGANIZATION_TYPE_Realtor', 0L, 0.0],
       ['LIVE_REGION_NOT_WORK_REGION', 0L, 0.0],
       ['LIVE_CITY_NOT_WORK_CITY', 0L, 0.0],
       ['ORGANIZATION_TYPE_Religion', 0L, 0.0],
       ['ORGANIZATION_TYPE_Restaurant', 0L, 0.0],
       ['ORGANIZATION_TYPE_School', 0L, 0.0],
       ['HOUR_APPR_PROCESS_START', 0L, 0.0],
       ['ORGANIZATION_TYPE_Mobile', 0L, 0.0],
       ['ORGANIZATION_TYPE_Security', 0L, 0.0],
       ['ORGANIZATION_TYPE_Security Ministries', 0L, 0.0],
       ['ORGANIZATION_TYPE_Self-employed', 0L, 0.0],
       ['ORGANIZATION_TYPE_Services', 0L, 0.0],
       ['ORGANIZATION_TYPE_Telecom', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 1', 0L, 0.0],
       ['FLAG_WORK_PHONE', 0L, 0.0],
       ['FLAG_PHONE', 0L, 0.0],
       ['ORGANIZATION_TYPE_Other', 0L, 0.0],
       ['ORGANIZATION_TYPE_Military', 0L, 0.0],
       ['FLAG_OWN_CAR', 0L, 0.0],
       ['ORGANIZATION_TYPE_Medicine', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 3', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 4', 0L, 0.0],
       ['REG_REGION_NOT_WORK_REGION', 0L, 0.0],
       ['REG_REGION_NOT_LIVE_REGION', 0L, 0.0],
       ['REG_CITY_NOT_WORK_CITY', 0L, 0.0],
       ['REG_CITY_NOT_LIVE_CITY', 0L, 0.0],
       ['REGION_RATING_CLIENT_W_CITY', 0L, 0.0],
       ['REGION_RATING_CLIENT', 0L, 0.0],
       ['REGION_POPULATION_RELATIVE', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 5', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 6', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 7', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 8', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 9', 0L, 0.0],
       ['ORGANIZATION_TYPE_Insurance', 0L, 0.0],
       ['ORGANIZATION_TYPE_Kindergarten', 0L, 0.0],
       ['ORGANIZATION_TYPE_Legal Services', 0L, 0.0],
       ['FLAG_OWN_REALTY', 0L, 0.0],
       ['FLAG_MOBIL', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 13', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_FRIDAY', 0L, 0.0],
       ['CODE_GENDER', 0L, 0.0],
       ['CNT_FAM_MEMBERS', 0L, 0.0],
       ['CNT_CHILDREN', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Monolithic', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Others', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Panel', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Stone, brick', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Wooden', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_MONDAY', 0L, 0.0],
       ['FLAG_EMP_PHONE', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_SATURDAY', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_SUNDAY', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_THURSDAY', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_TUESDAY', 0L, 0.0],
       ['WEEKDAY_APPR_PROCESS_START_WEDNESDAY', 0L, 0.0],
       ['AMT_INCOME_TOTAL', 0L, 0.0],
       ['AMT_GOODS_PRICE', 0L, 0.0],
       ['AMT_CREDIT', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Mixed', 0L, 0.0],
       ['WALLSMATERIAL_MODE_Block', 0L, 0.0],
       ['ORGANIZATION_TYPE_XNA', 0L, 0.0],
       ['DAYS_BIRTH', 0L, 0.0],
       ['FLAG_EMAIL', 0L, 0.0],
       ['FLAG_DOCUMENT_3', 0L, 0.0],
       ['FLAG_CONT_MOBILE', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 2', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 3', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 4', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 5', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 6', 0L, 0.0],
       ['ORGANIZATION_TYPE_Trade: type 7', 0L, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 1', 0L, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 2', 0L, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 3', 0L, 0.0],
       ['ORGANIZATION_TYPE_Transport: type 4', 0L, 0.0],
       ['DAYS_REGISTRATION', 0L, 0.0],
       ['DAYS_LAST_PHONE_CHANGE', 0L, 0.0],
       ['DAYS_ID_PUBLISH', 0L, 0.0],
       ['ORGANIZATION_TYPE_University', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 2', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 12', 0L, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 3', 0L, 0.0],
       ['NAME_TYPE_SUITE_Children', 0L, 0.0],
       ['OCCUPATION_TYPE_Cleaning staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Accountants', 0L, 0.0],
       ['NAME_TYPE_SUITE_Unaccompanied', 0L, 0.0],
       ['NAME_TYPE_SUITE_Spouse, partner', 0L, 0.0],
       ['NAME_TYPE_SUITE_Other_B', 0L, 0.0],
       ['NAME_TYPE_SUITE_Other_A', 0L, 0.0],
       ['NAME_TYPE_SUITE_Group of people', 0L, 0.0],
       ['NAME_TYPE_SUITE_Family', 0L, 0.0],
       ['NAME_INCOME_TYPE_Working', 0L, 0.0],
       ['NAME_HOUSING_TYPE_Office apartment', 0L, 0.0],
       ['NAME_INCOME_TYPE_Unemployed', 0L, 0.0],
       ['NAME_INCOME_TYPE_Student', 0L, 0.0],
       ['NAME_INCOME_TYPE_State servant', 0L, 0.0],
       ['NAME_INCOME_TYPE_Pensioner', 0L, 0.0],
       ['NAME_INCOME_TYPE_Maternity leave', 0L, 0.0],
       ['NAME_INCOME_TYPE_Commercial associate', 0L, 0.0],
       ['NAME_INCOME_TYPE_Businessman', 0L, 0.0],
       ['NAME_HOUSING_TYPE_With parents', 0L, 0.0],
       ['OCCUPATION_TYPE_Cooking staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Core staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Drivers', 0L, 0.0],
       ['OCCUPATION_TYPE_HR staff', 0L, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 2', 0L, 0.0],
       ['ORGANIZATION_TYPE_Business Entity Type 1', 0L, 0.0],
       ['ORGANIZATION_TYPE_Bank', 0L, 0.0],
       ['ORGANIZATION_TYPE_Agriculture', 0L, 0.0],
       ['ORGANIZATION_TYPE_Advertising', 0L, 0.0],
       ['OCCUPATION_TYPE_Waiters/barmen staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Security staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Secretaries', 0L, 0.0],
       ['OCCUPATION_TYPE_Sales staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Realty agents', 0L, 0.0],
       ['OCCUPATION_TYPE_Private service staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Medicine staff', 0L, 0.0],
       ['OCCUPATION_TYPE_Managers', 0L, 0.0],
       ['OCCUPATION_TYPE_Low-skill Laborers', 0L, 0.0],
       ['OCCUPATION_TYPE_Laborers', 0L, 0.0],
       ['OCCUPATION_TYPE_IT staff', 0L, 0.0],
       ['OCCUPATION_TYPE_High skill tech staff', 0L, 0.0],
       ['NAME_HOUSING_TYPE_Rented apartment', 0L, 0.0],
       ['NAME_HOUSING_TYPE_Municipal apartment', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 11', 0L, 0.0],
       ['ORGANIZATION_TYPE_Emergency', 0L, 0.0],
       ['EMERGENCYSTATE_MODE_Yes', 0L, 0.0],
       ['EMERGENCYSTATE_MODE_No', 0L, 0.0],
       ['NEW_CREDIT_TO_INCOME_RATIO', 0L, 0.0],
       ['ORGANIZATION_TYPE_Construction', 0L, 0.0],
       ['NEW_PHONE_TO_BIRTH_RATIO', 0L, 0.0],
       ['ORGANIZATION_TYPE_Culture', 0L, 0.0],
       ['ORGANIZATION_TYPE_Electricity', 0L, 0.0],
       ['NEW_SCORES_STD', 0L, 0.0],
       ['ORGANIZATION_TYPE_Government', 0L, 0.0],
       ['NAME_HOUSING_TYPE_House / apartment', 0L, 0.0],
       ['ORGANIZATION_TYPE_Hotel', 0L, 0.0],
       ['NEW_INC_BY_ORG', 0L, 0.0],
       ['NEW_INC_PER_CHLD', 0L, 0.0],
       ['NEW_LIVE_IND_SUM', 0L, 0.0],
       ['NEW_DOC_IND_KURT', 0L, 0.0],
       ['NEW_CREDIT_TO_GOODS_RATIO', 0L, 0.0],
       ['ORGANIZATION_TYPE_Housing', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 1', 0L, 0.0],
       ['FONDKAPREMONT_MODE_not specified', 0L, 0.0],
       ['FONDKAPREMONT_MODE_org spec account', 0L, 0.0],
       ['FONDKAPREMONT_MODE_reg oper account', 0L, 0.0],
       ['FONDKAPREMONT_MODE_reg oper spec account', 0L, 0.0],
       ['NAME_HOUSING_TYPE_Co-op apartment', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Widow', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Unknown', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Single / not married', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Separated', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Married', 0L, 0.0],
       ['NAME_FAMILY_STATUS_Civil marriage', 0L, 0.0],
       ['NAME_EDUCATION_TYPE_Secondary / secondary special', 0L, 0.0],
       ['NAME_EDUCATION_TYPE_Lower secondary', 0L, 0.0],
       ['NAME_EDUCATION_TYPE_Incomplete higher', 0L, 0.0],
       ['NAME_EDUCATION_TYPE_Higher education', 0L, 0.0],
       ['NAME_EDUCATION_TYPE_Academic degree', 0L, 0.0],
       ['NAME_CONTRACT_TYPE_Revolving loans', 0L, 0.0],
       ['NAME_CONTRACT_TYPE_Cash loans', 0L, 0.0],
       ['HOUSETYPE_MODE_terraced house', 0L, 0.0],
       ['HOUSETYPE_MODE_specific housing', 0L, 0.0],
       ['HOUSETYPE_MODE_block of flats', 0L, 0.0],
       ['ORGANIZATION_TYPE_Industry: type 10', 0L, 0.0]], dtype=object)

In [43]:
nomiss_feats=[]
for e in range(0, L2.shape[0]):
    nomiss_feats.append(L3[e][0])
nomiss_feats

['ORGANIZATION_TYPE_Cleaning',
 'ORGANIZATION_TYPE_Police',
 'ORGANIZATION_TYPE_Postal',
 'ORGANIZATION_TYPE_Realtor',
 'LIVE_REGION_NOT_WORK_REGION',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE_Religion',
 'ORGANIZATION_TYPE_Restaurant',
 'ORGANIZATION_TYPE_School',
 'HOUR_APPR_PROCESS_START',
 'ORGANIZATION_TYPE_Mobile',
 'ORGANIZATION_TYPE_Security',
 'ORGANIZATION_TYPE_Security Ministries',
 'ORGANIZATION_TYPE_Self-employed',
 'ORGANIZATION_TYPE_Services',
 'ORGANIZATION_TYPE_Telecom',
 'ORGANIZATION_TYPE_Trade: type 1',
 'FLAG_WORK_PHONE',
 'FLAG_PHONE',
 'ORGANIZATION_TYPE_Other',
 'ORGANIZATION_TYPE_Military',
 'FLAG_OWN_CAR',
 'ORGANIZATION_TYPE_Medicine',
 'ORGANIZATION_TYPE_Industry: type 3',
 'ORGANIZATION_TYPE_Industry: type 4',
 'REG_REGION_NOT_WORK_REGION',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_CITY_NOT_WORK_CITY',
 'REG_CITY_NOT_LIVE_CITY',
 'REGION_RATING_CLIENT_W_CITY',
 'REGION_RATING_CLIENT',
 'REGION_POPULATION_RELATIVE',
 'ORGANIZATION_TYPE_Industry: type 5',
 'ORGANIZATION_TYPE_Industry: type 6',
 'ORGANIZATION_TYPE_Industry: type 7',
 'ORGANIZATION_TYPE_Industry: type 8',
 'ORGANIZATION_TYPE_Industry: type 9',
 'ORGANIZATION_TYPE_Insurance',
 'ORGANIZATION_TYPE_Kindergarten',
 'ORGANIZATION_TYPE_Legal Services',
 'FLAG_OWN_REALTY',
 'FLAG_MOBIL',
 'ORGANIZATION_TYPE_Industry: type 13',
 'WEEKDAY_APPR_PROCESS_START_FRIDAY',
 'CODE_GENDER',
 'CNT_FAM_MEMBERS',
 'CNT_CHILDREN',
 'WALLSMATERIAL_MODE_Monolithic',
 'WALLSMATERIAL_MODE_Others',
 'WALLSMATERIAL_MODE_Panel',
 'WALLSMATERIAL_MODE_Stone, brick',
 'WALLSMATERIAL_MODE_Wooden',
 'WEEKDAY_APPR_PROCESS_START_MONDAY',
 'FLAG_EMP_PHONE',
 'WEEKDAY_APPR_PROCESS_START_SATURDAY',
 'WEEKDAY_APPR_PROCESS_START_SUNDAY',
 'WEEKDAY_APPR_PROCESS_START_THURSDAY',
 'WEEKDAY_APPR_PROCESS_START_TUESDAY',
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
 'AMT_INCOME_TOTAL',
 'AMT_GOODS_PRICE',
 'AMT_CREDIT',
 'WALLSMATERIAL_MODE_Mixed',
 'WALLSMATERIAL_MODE_Block',
 'ORGANIZATION_TYPE_XNA',
 'DAYS_BIRTH',
 'FLAG_EMAIL',
 'FLAG_DOCUMENT_3',
 'FLAG_CONT_MOBILE',
 'ORGANIZATION_TYPE_Trade: type 2',
 'ORGANIZATION_TYPE_Trade: type 3',
 'ORGANIZATION_TYPE_Trade: type 4',
 'ORGANIZATION_TYPE_Trade: type 5',
 'ORGANIZATION_TYPE_Trade: type 6',
 'ORGANIZATION_TYPE_Trade: type 7',
 'ORGANIZATION_TYPE_Transport: type 1',
 'ORGANIZATION_TYPE_Transport: type 2',
 'ORGANIZATION_TYPE_Transport: type 3',
 'ORGANIZATION_TYPE_Transport: type 4',
 'DAYS_REGISTRATION',
 'DAYS_LAST_PHONE_CHANGE',
 'DAYS_ID_PUBLISH',
 'ORGANIZATION_TYPE_University',
 'ORGANIZATION_TYPE_Industry: type 2',
 'ORGANIZATION_TYPE_Industry: type 12',
 'ORGANIZATION_TYPE_Business Entity Type 3',
 'NAME_TYPE_SUITE_Children',
 'OCCUPATION_TYPE_Cleaning staff',
 'OCCUPATION_TYPE_Accountants',
 'NAME_TYPE_SUITE_Unaccompanied',
 'NAME_TYPE_SUITE_Spouse, partner',
 'NAME_TYPE_SUITE_Other_B',
 'NAME_TYPE_SUITE_Other_A',
 'NAME_TYPE_SUITE_Group of people',
 'NAME_TYPE_SUITE_Family',
 'NAME_INCOME_TYPE_Working',
 'NAME_HOUSING_TYPE_Office apartment',
 'NAME_INCOME_TYPE_Unemployed',
 'NAME_INCOME_TYPE_Student',
 'NAME_INCOME_TYPE_State servant',
 'NAME_INCOME_TYPE_Pensioner',
 'NAME_INCOME_TYPE_Maternity leave',
 'NAME_INCOME_TYPE_Commercial associate',
 'NAME_INCOME_TYPE_Businessman',
 'NAME_HOUSING_TYPE_With parents',
 'OCCUPATION_TYPE_Cooking staff',
 'OCCUPATION_TYPE_Core staff',
 'OCCUPATION_TYPE_Drivers',
 'OCCUPATION_TYPE_HR staff',
 'ORGANIZATION_TYPE_Business Entity Type 2',
 'ORGANIZATION_TYPE_Business Entity Type 1',
 'ORGANIZATION_TYPE_Bank',
 'ORGANIZATION_TYPE_Agriculture',
 'ORGANIZATION_TYPE_Advertising',
 'OCCUPATION_TYPE_Waiters/barmen staff',
 'OCCUPATION_TYPE_Security staff',
 'OCCUPATION_TYPE_Secretaries',
 'OCCUPATION_TYPE_Sales staff',
 'OCCUPATION_TYPE_Realty agents',
 'OCCUPATION_TYPE_Private service staff',
 'OCCUPATION_TYPE_Medicine staff',
 'OCCUPATION_TYPE_Managers',
 'OCCUPATION_TYPE_Low-skill Laborers',
 'OCCUPATION_TYPE_Laborers',
 'OCCUPATION_TYPE_IT staff',
 'OCCUPATION_TYPE_High skill tech staff',
 'NAME_HOUSING_TYPE_Rented apartment',
 'NAME_HOUSING_TYPE_Municipal apartment',
 'ORGANIZATION_TYPE_Industry: type 11',
 'ORGANIZATION_TYPE_Emergency',
 'EMERGENCYSTATE_MODE_Yes',
 'EMERGENCYSTATE_MODE_No',
 'NEW_CREDIT_TO_INCOME_RATIO',
 'ORGANIZATION_TYPE_Construction',
 'NEW_PHONE_TO_BIRTH_RATIO',
 'ORGANIZATION_TYPE_Culture',
 'ORGANIZATION_TYPE_Electricity',
 'NEW_SCORES_STD',
 'ORGANIZATION_TYPE_Government',
 'NAME_HOUSING_TYPE_House / apartment',
 'ORGANIZATION_TYPE_Hotel',
 'NEW_INC_BY_ORG',
 'NEW_INC_PER_CHLD',
 'NEW_LIVE_IND_SUM',
 'NEW_DOC_IND_KURT',
 'NEW_CREDIT_TO_GOODS_RATIO',
 'ORGANIZATION_TYPE_Housing',
 'ORGANIZATION_TYPE_Industry: type 1',
 'FONDKAPREMONT_MODE_not specified',
 'FONDKAPREMONT_MODE_org spec account',
 'FONDKAPREMONT_MODE_reg oper account',
 'FONDKAPREMONT_MODE_reg oper spec account',
 'NAME_HOUSING_TYPE_Co-op apartment',
 'NAME_FAMILY_STATUS_Widow',
 'NAME_FAMILY_STATUS_Unknown',
 'NAME_FAMILY_STATUS_Single / not married',
 'NAME_FAMILY_STATUS_Separated',
 'NAME_FAMILY_STATUS_Married',
 'NAME_FAMILY_STATUS_Civil marriage',
 'NAME_EDUCATION_TYPE_Secondary / secondary special',
 'NAME_EDUCATION_TYPE_Lower secondary',
 'NAME_EDUCATION_TYPE_Incomplete higher',
 'NAME_EDUCATION_TYPE_Higher education',
 'NAME_EDUCATION_TYPE_Academic degree',
 'NAME_CONTRACT_TYPE_Revolving loans',
 'NAME_CONTRACT_TYPE_Cash loans',
 'HOUSETYPE_MODE_terraced house',
 'HOUSETYPE_MODE_specific housing',
 'HOUSETYPE_MODE_block of flats',
 'ORGANIZATION_TYPE_Industry: type 10']

In [44]:
del missing_T
del L2
del L3
#del nomiss_feats
gc.collect()

425

In [45]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

for f in T.columns:
    if f in nomiss_feats:
        T[f] = scaler.fit_transform(T[f].values.reshape(-1,1))
T

C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_YEAR,...,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
307507,20560.5,0.238037,0.184049,0.024654,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307508,17370.0,0.080785,0.061350,0.016440,0.0,0.0,0.0,0.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307509,69777.0,0.280965,0.265849,0.040054,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
307510,49018.5,0.695297,0.695297,0.065721,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,49.0
307511,32067.0,0.263804,0.263804,0.034920,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307512,34600.5,0.415673,0.347648,0.055454,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,84.0
307513,22117.5,0.206417,0.149284,0.034920,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307514,14220.0,0.061350,0.061350,0.031840,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307515,28957.5,0.145374,0.122699,0.065721,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,15.0
307516,5337.0,0.000000,0.000000,0.030814,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,87.0
307517,25447.5,0.286299,0.286299,0.009253,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307518,16848.0,0.098442,0.077710,0.024654,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,28.0
307519,23539.5,0.114192,0.081800,0.050321,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307520,18535.5,0.143149,0.143149,0.014387,0.0,0.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307521,7875.0,0.051125,0.051125,0.034920,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307522,21690.0,0.114192,0.081800,0.034920,0.0,0.0,0.0,1.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307523,26041.5,0.164744,0.143149,0.040054,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,79.0
307524,22117.5,0.206417,0.149284,0.014387,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307525,23526.0,0.175542,0.143149,0.045187,0.0,0.0,0.0,3.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307526,46741.5,0.197000,0.186094,0.033894,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307527,19242.0,0.081800,0.081800,0.016440,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307528,16443.0,0.100728,0.071575,0.029787,0.0,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307529,27702.0,0.224949,0.224949,0.024654,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,12.0
307530,42493.5,0.576329,0.439673,0.070854,0.0,0.0,0.0,0.0,0.0,6.0,...,0.0,1.0,0.142857,1.0,0.142857,0.0,0.0,0.0,0.0,7.0
307531,29245.5,0.224540,0.184049,0.029787,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,96.0
307532,12334.5,0.081800,0.081800,0.011307,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307533,10759.5,0.095902,0.061350,0.019520,0.0,0.0,0.0,0.0,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307534,25726.5,0.207391,0.169734,0.045187,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,11.0
307535,23107.5,0.184049,0.184049,0.014387,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307536,34074.0,0.408998,0.408998,0.075988,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
356221,43366.5,0.228254,0.204499,0.075988,0.0,0.0,0.0,2.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356222,57519.0,0.388548,0.388548,0.065721,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356223,16398.0,0.124356,0.077710,0.024654,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356224,13455.0,0.061350,0.061350,0.012334,0.0,0.0,0.0,2.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356225,19530.0,0.143149,0.143149,0.045187,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356226,35374.5,0.293258,0.229039,0.019520,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,15.0
356227,23134.5,0.126544,0.102249,0.032867,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356228,37129.5,0.192380,0.153374,0.023627,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356229,13284.0,0.055215,0.055215,0.044161,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356230,16213.5,0.122699,0.122699,0.009253,0.0,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356231,17707.5,0.213456,0.155419,0.019520,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356232,24543.0,0.184049,0.184049,0.004120,0.0,0.0,0.0,1.0,0.0,2.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,79.0
356233,37917.0,0.435055,0.364008,0.045187,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,24.0
356234,15291.0,0.047378,0.040900,0.034920,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356235,38398.5,0.291018,0.245399,0.050321,0.0,0.0,0.0,1.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,94.0
356236,16020.0,0.040900,0.040900,0.012334,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356237,40824.0,0.181820,0.163599,0.029787,0.0,0.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356238,28890.0,0.184049,0.184049,0.019520,0.0,0.0,0.0,1.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356239,54382.5,0.197546,0.184049,0.036974,0.0,0.0,0.0,1.0,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356240,37764.0,0.455701,0.390593,0.024654,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356241,46660.5,0.359321,0.327198,0.024654,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,14.0
356242,7411.5,0.029088,0.020450,0.013360,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356243,48888.0,0.206994,0.184049,0.029787,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356244,28570.5,0.143149,0.143149,0.055454,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,23.0
356245,23112.0,0.094080,0.078419,0.024654,0.0,0.0,0.0,2.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356246,17473.5,0.167035,0.102249,0.021574,0.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356247,31909.5,0.262401,0.204499,0.029787,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356248,33205.5,0.122699,0.122699,0.040054,0.0,0.0,0.0,3.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356249,25128.0,0.184049,0.184049,0.045187,0.0,0.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356250,24709.5,0.121685,0.102249,0.024654,0.0,0.0,0.0,1.0,0.0,4.0,...,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,12.0

In [46]:
del nomiss_feats
gc.collect()

49

In [ ]:
model=build_neural_network()
restorer=tf.train.Saver()
with tf.Session() as sess:
    restorer.restore(sess,"./home_credit.ckpt")
    feed={
        model.inputs:T,
        model.is_training:False
    }
    test_predict=sess.run(model.predicted,feed_dict=feed)
    
test_predict[:10]

307507